version: "2"
services:
  base:
    build:
      context: ..
      dockerfile: SemaphoreCI/Dockerfile-base
    image: mytardis/mytardis-base
  builder:
    build:
      context: ..
      dockerfile: SemaphoreCI/Dockerfile-build
    volumes:
      - ../wheelhouse:/wheelhouse
    depends_on:
      - base
